#!/usr/bin/env ruby

ENV['BUNDLE_GEMFILE'] = File.expand_path('../Gemfile.sidekiq-web', __FILE__)

require 'bundler/setup'
require 'sinatra'
require 'sidekiq'
require 'sidekiq/web'

Sidekiq.redis = {
  namespace: 'pudding',
  size: 30,
  url: ENV[ENV['REDIS_PROVIDER'] || 'REDIS_URL'] || 'redis://localhost:6379/0'
}

configure do
  use Rack::Auth::Basic do |username, password|
    ENV['SIDEKIQ_WEB_AUTH_BASIC'] && (
      "#{username}:#{password}" == ENV['SIDEKIQ_WEB_AUTH_BASIC']
    )
  end if ENV['DYNO']
end

class App < Sidekiq::Web
  run!
end
